name: github pages

on:
  push:
    branches:
      - source # Set a branch name to trigger deployment
    paths-ignore:
      - 'share/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Pull Theme
        run: |
          rm -rf public
          rm -rf themes
          git clone https://github.com/keaising/kitto.git themes/kitto

      - name: Build
        run: hugo --buildFuture

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          keep_files: true
          full_commit_message: ${{ github.event.head_commit.message }}
